default: &default
  adapter: postgresql
  host: localhost

development:
  <<: *default
  database: tracker_development

test:
  <<: *default
  database: tracker_test

production:
  <<: *default
  database: tracker_production
  encoding: unicode
  pool: 5
