default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  hots: localhost

development:
  <<: *default
  database: tracker_development

test:
  <<: *default
  database: tracker_test

production:
  <<: *default
  database: tracker_production
  username: tracker
  password: <%= ENV['TRACKER_DATABASE_PASSWORD'] %>
